version: '3.8'

services:
  db:
    image: postgres:14
    container_name: quill-db
    restart: always
    ports:
      - "5432:5432"
    env_file: 
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: quill-ai
    restart: always
    ports:
      - "5000:5000"
    env_file: 
      - .env
    depends_on:
      - db

volumes:
  pgdata:
