apiVersion: apps/v1
kind: Deployment
metadata:
  name: quill-ai
spec:
  replicas: 3
  selector:
    matchLabels:
      app: quill-ai
  template:
    metadata:
      labels:
        app: quill-ai
    spec:
      containers:
        - name: quill-ai
          image: ${{ secrets.ECR_REPOSITORY }}:latest
          ports:
            - containerPort: 5000
          envFrom:
            - secretRef:
                name: quill-ai-secrets
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"    
---
apiVersion: v1
kind: Service
metadata:
  name: quill-ai-service
spec:
  selector:
    app: quill-ai
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
